### ISSUE TITLE
/home/Sign_up crashing

### ISSUE THREAD

**Issue by dtjm** [dtjm/textdropapp.com#122]
2012-05-25T05:06:36+00:00 app[web.1]: [worker7] Error rendering /home/Sign_up [Error: Can't set headers after they are sent.]
2012-05-25T05:06:36+00:00 app[web.1]: [worker7] Error rendering /home/Sign_up [Error: Can't set headers after they are sent.]
2012-05-25T05:06:36+00:00 app[web.1]: 
2012-05-25T05:06:36+00:00 app[web.1]: http.js:530
2012-05-25T05:06:36+00:00 app[web.1]:     throw new Error("Can't set headers after they are sent.");
2012-05-25T05:06:36+00:00 app[web.1]:           ^
2012-05-25T05:06:36+00:00 app[web.1]: Error: Can't set headers after they are sent.
2012-05-25T05:06:36+00:00 app[web.1]:     at ServerResponse.<anonymous> (http.js:530:11)
2012-05-25T05:06:36+00:00 app[web.1]:     at ServerResponse.setHeader (/app/node_modules/express/node_modules/connect/lib/patch.js:62:20)
2012-05-25T05:06:36+00:00 app[web.1]:     at ServerResponse.header (/app/node_modules/express/lib/response.js:280:8)
2012-05-25T05:06:36+00:00 app[web.1]:     at ServerResponse.json (/app/node_modules/express/lib/response.js:135:8)
2012-05-25T05:06:36+00:00 app[web.1]:     at ServerResponse.send (/app/node_modules/express/lib/response.js:78:21)
2012-05-25T05:06:36+00:00 app[web.1]:     at /app/routes/public-routes.js:167:32
2012-05-25T05:06:36+00:00 app[web.1]:     at ServerResponse.render (/app/node_modules/express/lib/view.js:322:7)
2012-05-25T05:06:36+00:00 app[web.1]:     at [object Object].callback (/app/routes/public-routes.js:157:17)
2012-05-25T05:06:36+00:00 app[web.1]:     at Timer._callback (/app/node_modules/waitgroup/waitgroup.js:43:22)
2012-05-25T05:06:36+00:00 app[web.1]:     at Timer.<anonymous> (timers.js:172:14)

**Comment by dtjm** [comment]
still broken. try force-refreshing it a lot

**Comment by dtjm** [comment]
fixed in 3.6.4
