### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by dtjm** [dtjm/textdropapp.com#139]
```
2012-08-21T17:48:18+00:00 app[web.1]: 
2012-08-21T17:48:18+00:00 app[web.1]: undefined:2
2012-08-21T17:48:18+00:00 app[web.1]: <html>
2012-08-21T17:48:18+00:00 app[web.1]: ^
2012-08-21T17:48:18+00:00 app[web.1]: SyntaxError: Unexpected token <
2012-08-21T17:48:18+00:00 app[web.1]:     at Object.parse (native)
2012-08-21T17:48:18+00:00 app[web.1]:     at Request.exports.app.createClient.put [as _callback] (/app/node_modules/dbox/dbox.js:112:46)
2012-08-21T17:48:18+00:00 app[web.1]:     at Request.init.self.callback (/app/node_modules/dbox/node_modules/request/main.js:119:22)
2012-08-21T17:48:18+00:00 app[web.1]:     at Request.<anonymous> (/app/node_modules/dbox/node_modules/request/main.js:525:16)
2012-08-21T17:48:18+00:00 app[web.1]:     at Request.EventEmitter.emit (events.js:88:17)
2012-08-21T17:48:18+00:00 app[web.1]:     at IncomingMessage.Request.start.self.req.self.httpModule.request.buffer (/app/node_modules/dbox/node_modules/request/main.js:484:14)
2012-08-21T17:48:18+00:00 app[web.1]:     at IncomingMessage.EventEmitter.emit (events.js:115:20)
2012-08-21T17:48:18+00:00 app[web.1]:     at IncomingMessage._emitEnd (http.js:366:10)
2012-08-21T17:48:18+00:00 app[web.1]:     at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
2012-08-21T17:48:18+00:00 app[web.1]:     at CleartextStream.socketOnData [as ondata] (http.js:1356:20)
2012-08-21T17:48:19+00:00 heroku[router]: Error H13 (Connection closed without response) -> PUT www.textdropapp.com/dropbox/PlainText/http journal (Sam Nguyen's conflicted copy) (Sam Nguyen's conflicted copy).txt dyno=web.1 queue= wait= service= status=503 bytes=
2012-08-21T17:48:19+00:00 app[web.1]: worker.id=4 pid=undefined died
```

**Comment by dtjm** [comment]
upgraded to node-dbox 0.5.6

commit: https://github.com/sintaxi/node-dbox/commit/ee474657295aaca4f6d2d262cf55d87d9cf672a8
